apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
spec:
  containers:
  - name: mysql-container
    image: mysql:8
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_DATABASE
      value: "testdb"
    - name: MYSQL_USER
      value: "testuser"
    - name: MYSQL_PASSWORD
      value: "testpass"
    ports:
    - containerPort: 3306
